//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestiSpec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Antwoorden = new HashSet<Antwoorden>();
            this.Beschikbaarheid_inspecteurs = new HashSet<Beschikbaarheid_inspecteurs>();
            this.Opdracht = new HashSet<Opdracht>();
            this.Opdracht1 = new HashSet<Opdracht>();
        }
    
        public int AccountID { get; set; }
        public string Gebruikersnaam { get; set; }
        public string Wachtwoord { get; set; }
        public string Rol { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsel { get; set; }
        public string Achternaam { get; set; }
        public string Postcode { get; set; }
        public string Huisnummer { get; set; }
        public string Email { get; set; }
        public string Telefoonnummer { get; set; }
        public Nullable<System.DateTime> Datum_certificering { get; set; }
        public Nullable<System.DateTime> Einddatum_certificering { get; set; }
        public string IBAN { get; set; }
        public System.DateTime Laatste_weiziging { get; set; }
    
        public virtual Rol_lookup Rol_lookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antwoorden> Antwoorden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beschikbaarheid_inspecteurs> Beschikbaarheid_inspecteurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opdracht> Opdracht { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opdracht> Opdracht1 { get; set; }
    }
}
