
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FestiSpec.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Beschikbaarheid_inspecteurs
{

    public int MedewerkerID { get; set; }

    public System.DateTime Datum { get; set; }



    public virtual Account Account { get; set; }

}

}
