
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FestiSpec.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Contactpersoon
{

    public int ContactpersoonID { get; set; }

    public string KlantID { get; set; }

    public string Voornaam { get; set; }

    public string Tussenvoegsel { get; set; }

    public string Achternaam { get; set; }

    public string Email { get; set; }

    public string Telefoon { get; set; }

    public string Notities { get; set; }

    public System.DateTime Laatste_weiziging { get; set; }



    public virtual Klant Klant { get; set; }

}

}
