//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestiSpec.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FestiSpecEntities : DbContext
    {
        public FestiSpecEntities()
            : base("name=FestiSpecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Antwoorden> Antwoorden { get; set; }
        public virtual DbSet<Beschikbaarheid_inspecteurs> Beschikbaarheid_inspecteurs { get; set; }
        public virtual DbSet<Contactpersoon> Contactpersoon { get; set; }
        public virtual DbSet<Inspectieformulier> Inspectieformulier { get; set; }
        public virtual DbSet<Inspectieformulier_vragenlijst_combinatie> Inspectieformulier_vragenlijst_combinatie { get; set; }
        public virtual DbSet<Klant> Klant { get; set; }
        public virtual DbSet<Offerte> Offerte { get; set; }
        public virtual DbSet<Opdracht> Opdracht { get; set; }
        public virtual DbSet<Rapport_template> Rapport_template { get; set; }
        public virtual DbSet<Rol_lookup> Rol_lookup { get; set; }
        public virtual DbSet<Status_lookup> Status_lookup { get; set; }
        public virtual DbSet<Vraag_mogelijk_antwoord> Vraag_mogelijk_antwoord { get; set; }
        public virtual DbSet<Vraagtype_lookup> Vraagtype_lookup { get; set; }
        public virtual DbSet<Vraag> Vraag { get; set; }
    }
}
