
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FestiSpec.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Inspectieformulier_vragenlijst_combinatie
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Inspectieformulier_vragenlijst_combinatie()
    {

        this.Antwoorden = new HashSet<Antwoorden>();

    }


    public int VIC_ID { get; set; }

    public int InspectieformulierID { get; set; }

    public int VraagID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Antwoorden> Antwoorden { get; set; }

    public virtual Inspectieformulier Inspectieformulier { get; set; }

    public virtual Vraag Vraag { get; set; }

}

}
