//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestiSpec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspectieformulier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspectieformulier()
        {
            this.Inspectieformulier_vragenlijst_combinatie = new HashSet<Inspectieformulier_vragenlijst_combinatie>();
        }
    
        public int InspectieformulierID { get; set; }
        public string InspectieFormulierTitel { get; set; }
        public Nullable<System.DateTime> Datum_inspectie { get; set; }
        public string Locatie { get; set; }
        public Nullable<int> OpdrachtID { get; set; }
        public string Beschrijving { get; set; }
        public System.DateTime Laatste_weiziging { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectieformulier_vragenlijst_combinatie> Inspectieformulier_vragenlijst_combinatie { get; set; }
        public virtual Opdracht Opdracht { get; set; }
    }
}
