
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FestiSpec.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Klant
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Klant()
    {

        this.Contactpersoon = new HashSet<Contactpersoon>();

        this.Opdracht = new HashSet<Opdracht>();

    }


    public string KvK_nummer { get; set; }

    public string Naam { get; set; }

    public string Straatnaam { get; set; }

    public string Huisnummer { get; set; }

    public string Telefoonnummer { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public byte[] Klant_logo { get; set; }

    public System.DateTime Laatste_weiziging { get; set; }

    public string Stad { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contactpersoon> Contactpersoon { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Opdracht> Opdracht { get; set; }

}

}
